spring:
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: false
      hibernate.format_sql: true
      hibernate.generate_statistics: true

      # Coherence Related Config
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: com.oracle.coherence.hibernate.cache.v53.CoherenceRegionFactory
      hibernate.cache.use_query_cache: true
      com.oracle.coherence.hibernate.cache.cache_config_file_path: coherence-foo.xml
logging:
  level:
    com.oracle.coherence: debug
    org.springframework: info
